### PR TITLE
Frequency & impact are like outputs & outcomes

### PR DESCRIPTION
**Pull request by hiremaga**
I've often described frequency & impact as similar to outputs & outcomes respectively. I think this is well aligned with the existing descriptions, but adds additional guidance that I've seen reduce bias & subjectivity. I've used this description to guide folks sharing feedback toward concrete observations instead of subjective judgement.

This description of outcomes & outputs helped me: https://hbr.org/2012/11/its-not-just-semantics-managing-outcomes

"Outcomes are the difference made by the outputs: better traffic flow, shorter travel times, and fewer accidents."

"Outputs are important products, services, profits, and revenues: the What. Outcomes create meanings, relationships, and differences: the Why. Outputs, such as revenue and profit, enable us to fund outcomes; but without outcomes, there is no need for outputs."

### CODE REVIEW

**Comment by rosenhouse** [comment]
Cool!

I think this could be a valuable analogy.  I also like that you provide a somewhat deterministic algorithm for deciding which boxes to check.

cc @njbennett who recently shared some positive feedback about these current definitions of impact and frequency that this PR would replace.

@hiremaga Could you share a bit more about your thinking in having this PR *remove* the existing guidance (and the examples), rather than adding to them?

**Comment by hiremaga** [comment]
> Cool!
> 
> I think this could be a valuable analogy. I also like that you provide a somewhat deterministic algorithm for deciding which boxes to check.

Glad you feel this way. I'm curious what @rnandi and other managers think as well. Thanks for pinging @njbennett.

> Could you share a bit more about your thinking in having this PR remove the existing guidance (and the examples), rather than adding to them?

I started with the existing guidance and iterated in place to arrive at this suggestion. This PR includes some text from examples in the algorithm. I noticed the earlier examples had an if/then format and took inspiration from that. 

If this went too far and lost something important lets bring back what was lost. I do think there's value to ending up with a version that's succinct. So it's easier to digest and recall.

**Comment by rosenhouse** [comment]
Hi Abhi,

We just spent some time discussing this PR together.  We like the overall thrust but have some suggested edits before merging....

1. One path through the workflow that we might have lost in this change-set is "All boxes are optional."  That would be the case of "haven't observed the Pivot do this" AND "they haven't yet made a difference."  Maybe the line item just isn't applicable.  Could we find a place to add this back?

2. We understand how the "outputs vs outcomes" framing could be a valuable mental model for arriving at the workflow you've described here.  We're wondering if this framing belongs up-top, or maybe below the concrete workflow, as more of an aside or footnote.  If we're trying to keep things concise, as you mention, then perhaps putting it a bit out of the way could help people get to the most actionable bits quickly?

3. The line in "Frequency" about "a combination of these boxes" sparked a long dialog between us about whether input to the form should be "raw" from the Feedback Giver, or first "pre-processed" some by the manager of the Feedback Receiver.  If you assume the former, then using multiple check-boxes might be helpful, but if you assume the latter, then perhaps the "pre-processing" ought to narrow it down to a single box.  At this point, it seems like there's enough variance in recommended practice that we're not fully comfortable recommending that a Feedback Giver check a combination of boxes for Frequency.  Would you be ok with deferring this change?  We'd be happy to have a longer conversation about the intended workflows here.

Would you be open to making some of these changes?

Happy to chat on Zoom about this too if you like!

Thanks!

@rosenhouse and @rnandi

**Comment by hiremaga** [comment]
Thanks @rosenhouse and @rnandi. I've tried to incorporate the 3 changes you've suggested in 8d9dcb4. Did I understand what you meant correctly?

**Comment by rnandi** [comment]
Merged. Thanks for the quick turnaround on the PR, @hiremaga!

**Pull request merged**
