### PR TITLE
Skill: recruitment / growing the office.

### PR DESCRIPTION
**Pull request by genevieve**
There are additional skills in a document that require review and
rephrasing to either be more outcome-oriented or observable. If you are
interested in fleshing this niche skill matrix out further, please reach
out to myself or @ragaskar or @rnandi.

### CODE REVIEW

**Comment by zachgersh** [comment]
@genevieve - really glad that you changed this from a `niche skill`, when we know this is something that pivots should be encouraged to think about. This is one of those skills that helps create the sort of inclusive / diverse culture we want to see at our offices and it is absolutely invaluable.

The question I'd ask next is, why can't we make this something that is tied to p-level and increases a pivots overall compensation? This feels like a skill that is _critical_ to an organization that is growing and it'd be great to encourage people who enjoy it to specialize. We know that improving diversity positively impacts the quality of our product, this needs to be incentivized.

I'd like to propose a potential solution, take this skill even FURTHER. Moving this from `Skill: recruitment / growing the office` to `Skill: office leadership` fits in nicely with the other leadership skill centered around `product` and it also allows you to broaden the sorts of things that YOU very much tackled when working on this skill.

In addition, I believe labeling this as office leadership helps us draw a pretty direct line for pivots that potentially leads them onto the path of an engineering director.

cc @ragaskar / @rnandi

**Comment by rosenhouse** [comment]
Hi @genevieve,

Thank you for the PR, and sorry about the delay in response.  We're finally returning to full-time investment in this repo, at least temporarily.

We'd like to lower the barrier to delivering contributions like this one.   We have published a short [roadmap](https://github.com/pivotal-cf/areas-of-contribution/blob/master/CONTRIBUTING.md#roadmap) about our plans here.  

We don't have anything actionable for this PR just yet.  But once we've made concrete progress on that roadmap, we hope to come back with something more constructive, that will help us move this forward.

Thanks again for your patience.

**Comment by rosenhouse** [comment]
Hi @zachgersh,

Thanks for your feedback.  As I wrote above, we're working on formalizing the change review process for this sort of thing, and we intend for that to include materials to help contextualize the skill areas within the larger career paths that a Pivot might take.  Once that material is up, we can have a more productive conversation about some of your feedback here.

Happy to chat about this more face-to-face.

**Comment by genevieve** [comment]
Hey Gabe. The New York office is interested in using this niche skill so we would like to update the PR if the change review process has been formalized. Have there been any updates on that front?

**Comment by ebeer** [comment]
Given that the current Skills Matrix has this as an expectation of the P3 level: `Contributes to the positive culture of office, especially around inclusivity, safety, and empathy` and `Participates in the interview process` as an example of demonstrating P3 level, I'm wondering how not having this skill represented is in keeping with compatibility of these frameworks. 
(I also have opinions about labeling this as "niche", but that's another matter for a longer conversation.)

**Comment by rosenhouse** [comment]
Update: we now have [a contribution guide](https://github.com/pivotal-cf/areas-of-contribution/blob/master/CONTRIBUTING.md). 

There are some bits that still need to be documented fully, including #63 and that you need to run `tools/regenerate.sh`.  The other thing is: we haven't yet tested the tooling around adding a whole new area as this PR does.  I'm pretty sure it will break our current spreadsheet-and-form stuff in `tools/` but I don't think that should block review of the content of this PR.  If we want a new area, that ought to drive priorities for the tooling.

**Comment by rainmaker** [comment]
Hi Gen and other interested parties,

We'd like to merge this as a niche skill. We'd keep it as markdown to start, since the technical cost of adding a new skill area in the form is too great at the moment. 

The intent with the separation of niche skill is not to devalue them, nor to prevent them from being used in leveling/compensation conversations. In fact, the purpose of including these skills is for them to be used concretely in leveling conversations. However, many of these skills are subject-matter specific, diving deeper into certain areas, or are optional based on a particular engineer's interests. 

Another facet is to think of niche skill as an incubator for skill areas that individual pivots are developing for their own growth and leveling. As more pivots and managers start using a niche skill area, we would consider adding it to the central list. Some skills might stay "niche", and that's okay -- they still have a huge amount of value. In the end, we want to keep the central skill list focused on what most pivots will do from day 1.

I'll add some of this clarification to the README under `niche-skills/`, so it's more discoverable for people exploring the repo.

I've pulled your changes in, and am just doing some work on the directory structure and README. So, you should see this merged in a day or so.

**Pull request merged**
